version: '3.7'

services:
  react:
    container_name: react
    build:
      context: react
      dockerfile: react/Dockerfile
    volumes:
      - ".:/app"
    ports:
      - "9000:3001" # 외부:내부
    environment:
      - NODE_ENV=development
      - TZ=Asia/Seoul
    networks:
      - react
  nginx:
    container_name: nginx
    build:
      context: react
      dockerfile: react/nginx/dockerFile
    networks:
      - react
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - react
  db:
    image: mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: xiiulakalkjjqw7190
  adminer:
    image: adminer
    restart: 'always'
    ports:
      - "8001:8080"

networks:
  react:
